# Generated by Django 5.1 on 2024-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0003_modifier_menu_menuitem_cartitem_cartitemmodifier_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modifier",
            name="price_varies",
            field=models.BooleanField(default=False),
        ),
    ]
