# Generated by Django 5.1 on 2024-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_modifier_price_varies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifier",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
