# Generated by Django 5.1 on 2024-09-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_cartitem_created_at_cartitem_guest_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
