# Generated by Django 5.1 on 2024-09-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_restaurant_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
