# Generated by Django 5.1 on 2024-09-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_order_orderitem_orderitemmodifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_transfer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
