# Generated by Django 5.1 on 2024-09-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_order_stripe_transfer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="doordash_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
