# Generated by Django 4.2.13 on 2024-09-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_order_preparation_start_time_order_preparation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doordash_delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
