# Generated by Django 4.2.13 on 2024-09-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_digitalloyaltycard_menuitem_points_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='points_per_dollar',
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_per_100',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='userdigitalcard',
            name='unredeemed_rewards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='program_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('POINTS', 'Points per 100 Dollars')], max_length=10),
        ),
    ]
