# Generated by Django 4.2.13 on 2024-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_remove_loyaltyprogram_points_per_dollar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_required_modifiers',
            field=models.BooleanField(default=False),
        ),
    ]
