# Generated by Django 4.2.13 on 2024-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_menuitem_has_required_modifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='points_per_100',
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_per_dollar',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='program_type',
            field=models.CharField(choices=[('POINTS', 'Points per Dollar')], default='POINTS', max_length=10),
        ),
    ]
