# Generated by Django 4.2.13 on 2024-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_remove_loyaltyprogram_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='points_per_dollar',
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='menu_item_points_multiplier',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_per_100',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='program_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('POINTS', 'Points per 100 Dollars')], max_length=10),
        ),
    ]
