# Generated by Django 4.2.13 on 2024-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_remove_loyaltyprogram_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_free_item',
            field=models.BooleanField(default=False),
        ),
    ]
