# Generated by Django 4.2.13 on 2024-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_cartitem_is_free_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_free_item',
            field=models.BooleanField(default=False),
        ),
    ]
