# Generated by Django 4.2.13 on 2024-09-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_orderitem_is_free_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_free_item',
            new_name='is_reward_item',
        ),
    ]
