# Generated by Django 4.2.13 on 2024-09-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_rename_is_free_item_cartitem_is_reward_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_free_item',
            new_name='is_reward_item',
        ),
    ]
