# Generated by Django 4.2.13 on 2024-09-21 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_weeklysales'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weekly_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.weeklysales'),
        ),
    ]
