# Generated by Django 4.2.13 on 2024-09-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_order_weekly_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
