# Generated by Django 4.2.13 on 2024-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_order_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='doordash_external_business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='doordash_external_store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
