# Generated by Django 4.2.13 on 2024-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0028_order_customer_delivery_fee_order_store_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysales',
            name='total_customer_delivery_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklysales',
            name='total_delivery_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklysales',
            name='total_store_contributions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
