# Generated by Django 4.2.13 on 2024-09-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
