"""
Django settings for bite project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'restaurants.RestaurantUser'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)j2&o8u0&4p#@0-*ytsjo&bosaexb-+e!5=p4)$_pk&r1$)@n="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com', 'localhost', '127.0.0.1']

# Ensure SITE_URL is correctly set
SITE_URL = 'http://127.0.0.1:8000/'

SITE_ID = 1

ASGI_APPLICATION = 'bite.asgi.application'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "daphne",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "restaurants.apps.RestaurantsConfig",
    "channels",
    "celery",
    "twilio",
    "django_celery_results",
    "django_celery_beat",
    "background_task",
    "reportlab",
    "xhtml2pdf",
    "pytz",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "restaurants.context_processors.restaurant_context",
                "restaurants.context_processors.google_maps_api_key",
            ],
        },
    },
]

WSGI_APPLICATION = "bite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Add your DoorDash credentials
DOORDASH_DEVELOPER_ID = 'f7f962bb-3ff9-4827-85d4-d9c4e4f1a61f'
DOORDASH_KEY_ID = '9b9770cc-4e98-4e57-a111-809c5d44935c'
DOORDASH_SIGNING_SECRET_KEY = '5_6YP-SJ3VgycgkDyWzQZkRoTs5R2uU89HN4bIO8oQk'


# Stripe settings
# STRIPE_SECRET_KEY = 'sk_test_51P4gElP9SsicgG1jiHrOYu86MB4PNBRKMTxSgCHrCpPGaWrs68tkgtsUMx8CBZ7Nv0BXd9nFMAyuia4mSEo60Tdj00iH6Li1dk'
# STRIPE_PUBLISHABLE_KEY = 'pk_test_51P4gElP9SsicgG1jB3b9vewTDC2pbRh3YOUKAaavO88BIFyqQgIg3FJzmy9NDwitrtwS8BXHUYhG2R2WtuuqfLFw00ZdmOuvHt'
# STRIPE_MONTHLY_SUBSCRIPTION_PRICE_ID = 'price_1Pto1yP9SsicgG1jX4zJshHj'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


# Django Channels
ASGI_APPLICATION = 'bite.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Twilio Settings
# TWILIO_ACCOUNT_SID = 'AC3a77b6b74e5e6950d39a226ba984049c'
# TWILIO_AUTH_TOKEN = 'c80f3293f93903396a01d838300a40a5'
# TWILIO_PHONE_NUMBER = '+15752655076'

# WebSocket URL
WEBSOCKET_URL = 'ws://localhost:8000/ws/'  # Update this for production


LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Australia/Adelaide'

USE_I18N = True

USE_TZ = True

GOOGLE_MAPS_API_KEY = 'AIzaSyD_jODWQ-KDeU65Sr4xOALQsZ7mwI3q7h4'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


LOGIN_REDIRECT_URL = ''

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "missamaniaesthetics@gmail.com"
EMAIL_HOST_PASSWORD = "htvqrrnevbcyccku"
DEFAULT_FROM_EMAIL = "missamaniaesthetics@gmail.com"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Add this at the end of the file
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'restaurants/static'),
    ]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
